# Лабораторная работа №4
_Анализ и визуализация данных в Python_

Для начала о том, как пользоваться интерактивным блокнотом. Код помещается в ячейки, для выполнения кода в ячейке нужно кликнуть в ней мышкой, чтобы она выделилась, и нажать Shift-Enter. Поэкспериментируйте на ячейке ниже:

In [ ]:
1+1

Если в ячейке находятся несколько выражений, то результатом выполнения ячейки будет результат последнего выражения в ней:

In [ ]:
1+1
1+2

Теперь перейдём к работе с наборами данных при помощи бибилиотеки pandas

## Pandas
Для того, чтобы начать работать с pandas, как и всегда в python, его нужно импортировать. Обычно это делают так:

In [ ]:
import pandas as pd

Теперь попробуем загрузить набор данных. Для примера возьмём titanic.csv из каталога datasets, который можно загрузить при помощи функции read_csv:

In [ ]:
data = pd.read_csv('datasets/titanic.csv')

Взглянем на загруженные данные

In [ ]:
data

Можно попробовать найти в этих данных что-нибудь интересное. Например, посчитаем, какое количество мужчин и женщин было на корабле. Информация об этом хранится в столбце Sex, доступ к которому можно получить следующими способами

In [ ]:
data.Sex

или

In [ ]:
data['Sex']

Чтобы посчитать количество мужчин и женщин воспользуемся методом value_counts:

In [ ]:
data.Sex.value_counts()

Можем также получить процентное соотношение, указав флаг normalize:

In [ ]:
data.Sex.value_counts(normalize=True)

Можем определить среднюю цену билета, обратившись к столбцу Fare и воспользовавшись методом mean:

In [ ]:
data.Fare.mean()

Из нашего набора данных можно построить новый, выбрав только нужные столбцы при помощи свойства loc, например

In [ ]:
new_data = data.loc[:,['Name', 'Age']]
new_data

Можно отфильтровать только выживших

In [ ]:
survived = new_data[data.Survived==1]
survived

Полученный набор данных можно экспортировать обратно в csv функцией to_csv:

In [ ]:
survived.to_csv('survived.csv', index=False)

## Numpy
Numpy -- это библиотека для работы с массивами в Python. Список из стандартной библиотеки не достаточно производителен и имеет достаточно скудный интерфейс, чтобы использовать его для научных вычислений. Начнём с импорта библиотеки, который обычно записывают так:

In [1]:
import numpy as np

Создадим массив

In [3]:
arr = np.array([1,2,3,4])

Ровно как и с питоновскими списками можно получать элемент по индексу и делать слайсы:

In [5]:
arr[0]

1

In [6]:
arr[2:]

array([3, 4])

Но можно и доставать элементы по спи

А можно сделать из него матрицу 2x2:

In [10]:
m = arr.reshape((2,2))
m

array([[1, 2],
       [3, 4]])

Можно транспонировать эту матрицу

In [13]:
m.T

array([[1, 3],
       [2, 4]])

Вот так можно получить доступ к первой строке матрицы

In [16]:
m[0]

array([1, 2])

А вот так -- ко второму столбцу:

In [17]:
m[:,1]

array([2, 4])

Но самое интересное -- это применение операции ко всему массиву сразу. Например:

In [19]:
a = arr * 2
a

array([2, 4, 6, 8])

In [22]:
b = arr + 1
b

array([2, 3, 4, 5])

Можно даже применять арифметические операции для двух массивов поэлементно, при условии, что их размеры совпадают:

In [23]:
a + b

array([ 4,  7, 10, 13])

In [24]:
a - b

array([0, 1, 2, 3])

In [25]:
a * b

array([ 4, 12, 24, 40])

In [26]:
a / b

array([1.        , 1.33333333, 1.5       , 1.6       ])

In [27]:
a ** b

array([    4,    64,  1296, 32768])

Для нахождения скалярного произведения двух векторов есть оператор @

In [28]:
a @ b

80

Он же отвечает за умножение матрицы на вектор и перемножение матриц по правилу строка на столбец:

In [29]:
m @ a[:2]

array([10, 22])

In [30]:
m @ m

array([[ 7, 10],
       [15, 22]])

Также массив позволяет находить статистические характеристики

In [35]:
arr.sum(), arr.mean(), arr.std()

(10, 2.5, 1.118033988749895)

Можно фильтровать элементы массива по условию

In [37]:
arr[arr < 3]

array([1, 2])

## Matplotlib
построение простых графиков

## Scikit-learn
классификация и регрессия